#!/bin/bash

ID=$(id -u)
if [ $ID -ne 0 ]
then
   echo "ERROR:you are not root user,run with root user"
   exit 1 #you can give other than 0
else
   echo "you are root user"
fi
yum install mysql -y
if [ $? -ne 0 ]
then 
   echo "ERROR:MySql installation is unsuccessfull"
   exit 1
else 
   echo "MYSQL installed successfully"
fi


